### ISSUE TITLE
Deciding on ChunkSize

### ISSUE THREAD

**Issue by ZER-0-NE** [axiom-data-science/OrcaCNN#18]
This would be the best time to decide on the chunkSize since we'll be starting with the development of detection and classification model soon, so it's better to take a proper decision for this.
First of all, let me show the difference between the chunkSizes of `1s`, `2s` and `3s`:

1) When `chunkSize = 1s` (shows 3 spectrograms of 1s each )
![merge_from_ofoct](https://user-images.githubusercontent.com/19359908/59550723-bb78e800-8f8b-11e9-83e7-77430c3bce14.png)

2) When `chunkSize = 2s`
![Field Recordings NGOS_2008 field acoustic recordings_20080614 E03_1007_0000_0000](https://user-images.githubusercontent.com/19359908/59550753-262a2380-8f8c-11e9-816f-3b31158c6991.png)

3) When `chunkSize = 3s`

![Field Recordings NGOS_2008 field acoustic recordings_20080614 E03_1007_0000_0000](https://user-images.githubusercontent.com/19359908/59550756-39d58a00-8f8c-11e9-83ee-64df46f69653.png)

### Why I would choose 1s chunkSize?
**Keeping in mind the further classification and template matching/extraction methods:**

- First reason will be that the calls can be distinctly seen in each spectrogram. There is a very less chance of spectrograms overlapping for `1s` chunks than in the other `2s` and `3s` chunks. Since they won't overlap, the calls for further classification models can be directly taken as the whole spectrogram **without any template extraction process.**
- Though the 1s chunks are kinda blurry, the input to CNN model are often image sizes of around  224x224 dimension which is less than the dimension of each of the above chunks (around 600x400), so still the 1s chunk is a good choice.
- **The 3s chunks are also a good choice**, but much of the frequency-time area is merely noise, it's better to avoid it rather than crop each of them individually.

Template Matching also works out well for 1s chunks as I just tried, we can just loop over the 1s directory with the template for the given pod.
 
- Template (I've just cut out a portion spanning the width of the call since that would be enough right?):
<p align="center">
  <img  src=https://user-images.githubusercontent.com/19359908/59550984-0694fa00-8f90-11e9-8c63-50cade1f5749.png>
</p>

- Matched image result: 
![temp_match](https://user-images.githubusercontent.com/19359908/59550999-4d82ef80-8f90-11e9-854a-b731433ad07f.png)

So, is it a go for 1s chunks? @yosoyjay 
I would like to know if you have any ideas, criticism or suggestions.

**Comment by yosoyjay** [comment]
@ZER-0-NE Nice write up.  I appears to me that the advantages of using the 1s chunk (possibility of no template matching, minimizing possibility of overlap between calls) suggest you try that size first.  The only potential concern is if 1s is not sufficiently long to capture calls longer than 1s.  However, based on what I've seen in that, I don't believe that will be a problem.  So, I suggest trying the 1s chunk size, but to  keep in mind about the possibility of truncating longer calls.
