### ISSUE TITLE
MBARI data credit

### ISSUE THREAD

**Issue by danellecline** [axiom-data-science/OrcaCNN#29]
Please credit MBARI in this source code if their sound data was used in conjunction with Dan Olsen's data for validating model performance. This is per the collaboration agreement you have in place with them.  Thank you!

**Comment by yosoyjay** [comment]
Hi Danelle, sorry about that!  I added quick first cut of the acknowledgement and we're totally open to any suggested text or acknowledgements that you might prefer.

**Comment by yosoyjay** [comment]
Closing this following approval of text from John Ryan.

**Comment by danellecline** [comment]
Thank you!
