### ISSUE TITLE
Develop detection tool

### ISSUE THREAD

**Issue by yosoyjay** [axiom-data-science/OrcaCNN#3]
The primary job of this tool is to detect orca in passive acoustic datasets comprised of a pipeline consisting of stages to: 1) preprocess and standardize input data, 2) apply a model to identify the presence of orca within the dataset, 3) apply additional models to extract additional information about the orca call including signal type and pod, and 4) create a summary of the results of the pipeline indicating presence of orca along with time and any additional information.

The issue here is to apply the model(s) developed in  #2 to create stage 2 of the pipeline.

**Comment by ZER-0-NE** [comment]
Developed with the PR #24
