### ISSUE TITLE
Modification in the padding function in preprocessing.py

### ISSUE THREAD

**Issue by abhinav99ash29** [axiom-data-science/OrcaCNN#32]
```
if len(data) > input_length:    
        max_offset = len(data) - input_length    
        offset = np.random.randint(max_offset)    
        data = data[offset:(input_length + offset)]
````    

The case when input length is less than the actual data, in that case, wouldn't downsampling be better than chopping the data? Either downsampling the signal through averaging or skipping elements.

let n = length of actual data
let m = expected length
so an average of the signal for every n/m element occurs like below to make the array of size m

```
def average(arr, l = n/m):    
    end =  l * int(len(arr)/l)    
    return numpy.mean(arr[:end].reshape(-1, l), 1)    
```

And then pad some constant for remaining values if n/m is not an integer ?

**Comment by ZER-0-NE** [comment]
We decided chopping would work best mainly because of 2 reasons:

- There was a lot of data! So chopping off some audio part from long acoustic recordings would not matter much.
- Since the end goal was to work with spectrogram images, downsampling (or any other technique) would have distorted the calls in the resultant images. This would have further affected our model accuracies later.

**Comment by abhinav99ash29** [comment]
Regarding the first reason, if the difference between the two lengths is very high that may cause data loss?

The second reason I understand, actually I was using this preprocessing pipeline for raw data processing, hence thought of this issue, with spectrogram it's fine, my bad.

**Comment by ZER-0-NE** [comment]
If the difference between the two is very high, it would rather result in the last audio chunk having lots of noise along with a small portion of audio as meaningful data.

**Comment by abhinav99ash29** [comment]
Please correct me if I am wrong here!
```
for i, file in enumerate(glob.glob("*.wav")):
        print(f"Pre-Processing file: {file}")
        data, sr = librosa.core.load(file, sr=sampling_rate, res_type='kaiser_fast')

        # apply padding
        padded_data = padding(data, input_length)
```
If the difference between the two is high (actual duration >> expected duration obtained from the multiplication "sampling_rate * audio_duration") and now we try to take a small random subset of the actual data, padding the function is applied to each file in the loop then will it cause loss, if the duration argument supplied is much smaller?

Although, yeah the arguments given will be in consideration to the original files so it may be a rare occurrence. 

Edit - I am not referring to the chunks here I am referring to the for loop in the main function in preprocessing.py that is calling the padding function on each wav file and the input length or the expected length is related to the audio_duration parsed as arguments

**Comment by ZER-0-NE** [comment]
I'm not sure what exactly you mean by `actual` and `expected`. One is the audio duration of the input file and the other is the chunk_size or the duration of audio we want the files to be processed to. You might want to look at #18 to get some understanding of why 1s audio duration was chosen.
