### ISSUE TITLE
Develop summarizer

### ISSUE THREAD

**Issue by yosoyjay** [axiom-data-science/OrcaCNN#4]
The primary job of this tool is to detect orca in passive acoustic datasets comprised of a pipeline consisting of stages to: 1) preprocess and standardize input data, 2) apply a model to identify the presence of orca within the dataset, 3) apply additional models to extract additional information about the orca call including signal type and pod, and 4) create a summary of the results of the pipeline indicating presence of orca along with time and any additional information.

The issue here is to develop a tool that summarizes what was learned in #3 to create stage 4 of the pipeline.  The output should encapsulate all of the information extracted from the pipeline and output in formats amenable for humans (html?) and apis (json?).

**Comment by ZER-0-NE** [comment]
Hi @yosoyjay 
As mentioned in my proposal, the layout of the web-app can be adopted from the GUI shown below:


![](https://ars.els-cdn.com/content/image/1-s2.0-S0003682X18311241-gr9_lrg.jpg)

I've made a very simple front-end showing how the web-app can look like. It is just for demonstration purpose.
![Untitled presentation](https://user-images.githubusercontent.com/19359908/56151951-13b55d00-5fd0-11e9-8fa6-667755d214fe.png)

Once we upload the .wav file (**only .wav file** with the functionality to throw an error in case it's some other file) and the detection and pod-classification model weights as input (at first, I will keep my saved weights as default), the input wave plot and spectrogram will be shown on the right. (Or the detected killer whale call and the template matched). It depends.

I've considered the final output in HTML format here.
I would like to know your expectations here @yosoyjay

**Comment by yosoyjay** [comment]
I think this is a good start to get us thinking about what this should look like.

When I last spoke with Dan he emphasized that his first priority is getting the start and end times for the calls, so providing that information probably as text output is key.  I'd imagine .csv file would be ideal, but I'll check with him.

In my view I think showing the spectrogram with a bounding box indicating the location of the call would be nice, but I think getting Dan's thought's would be useful.

**Comment by ZER-0-NE** [comment]
Tossing the outputs in .csv file would mean that the web functionality should support getting multiple inputs where the start and end call (maybe multiple) of each sample would be shown in the csv file.

Indicating a single killer whale start and end call in a .csv file does not seem feasible. A simple HTML output will be good for that case.
> I think showing the spectrogram with a bounding box indicating the location of the call would be nice

Yeah. That was my initial thought too.
> but I think getting Dan's thought's would be useful.

Sure.

**Comment by kunakl07** [comment]
Hi @yosoyjay 
Here are the start and end time of the call that would be predicted by our model. Once our model has predicted the start and end time, a bounding box is created around the location of the call by maximizing the spectrogram. 
Here, I have taken overlapped various calls as I believe that the actual dataset would have calls overlapping each other such that there would be multiple calls occurring simultaneously and not at fixed intervals. 


![bandicam 2019-04-16 00-57-37-714](https://user-images.githubusercontent.com/36035718/56192273-e02ffe00-5fe2-11e9-840a-5306bc3fdecc.jpg)

![bandicam 2019-04-16 00-33-41-975](https://user-images.githubusercontent.com/36035718/56192485-56346500-5fe3-11e9-9409-4cd5a467dc3e.jpg)

This would be then converted to csv by using pandas dataframe 
```python
df.to_csv('example.csv')
``` 
and we would get a csv file specifying the start and end of the call

Hi @yosoyjay 
What are the further improvements that can be made?

**Comment by sainimohit23** [comment]
@yosoyjay  Sir, please take a look: https://github.com/sainimohit23/OrcaCNN-Demo/tree/master/5%20Full%20Pipeline
