### ISSUE TITLE
Normalization of audio does not produce any significant change

### ISSUE THREAD

**Issue by ZER-0-NE** [axiom-data-science/OrcaCNN#5]
Hi
I am trying to normalize the data that we have but I see that there is no significant change in the output waveform.
Do we need to consider this for pre-processing our data? or is it enough to just have all the samples downsampled to a particular sampling frequency and a fixed length?

```
def audio_norm(data):
    max_data = np.max(data)
    min_data = np.min(data)
    data = (data-min_data)/(max_data-min_data+1e-6)
    return data-0.5
```

![Screenshot from 2019-03-24 20-11-50](https://user-images.githubusercontent.com/19359908/54880977-1dd0b980-4e71-11e9-9d4c-ffe1f1b8493c.png)

**Comment by yosoyjay** [comment]
The focus here is to package the samples at the same sampling frequency and fixed length.

**Comment by ZER-0-NE** [comment]
Yeah, I guess then normalization would not work here.
