### ISSUE TITLE
Make data available to CoLab

### ISSUE THREAD

**Issue by yosoyjay** [axiom-data-science/OrcaCNN#7]
Ensure that data is available in CoLab as soon as it is delivered.

**Comment by yosoyjay** [comment]
Shane is going to load the data into the Axiom Google Drive share and we'll provide access for that directory to you.  I'll make sure that you had write permissions so that you can save the output models and such to the same account.

Example notebook of mounting Google Drive in CoLab: https://colab.research.google.com/notebooks/io.ipynb

**Comment by ZER-0-NE** [comment]
Sure. I'll look into that

**Comment by ZER-0-NE** [comment]
This stage was complete by using the `!gsutil` tool in Google Colab.
