### ISSUE TITLE
Develop data pre-processing methods

### ISSUE THREAD

**Issue by yosoyjay** [axiom-data-science/OrcaCNN#8]
The goal here is to develop the code to prepare the data for model development.  Existing methods have been prototyped before the start of the project and will form the basis of the methods.

- [x] Develop methods to standardize data
- [x] Develop methods to visualize the data
- [x] Convert exploratory code to Python script that can be deployed in backed of web app 
- [x] Ensure documentation is sufficiently adequate for new users to quickly pickup and apply

**Comment by ZER-0-NE** [comment]
How do we stand here? @yosoyjay

**Comment by yosoyjay** [comment]
Generally, it looks good. The only point I think that could use a little work is some docs describing how the classes are expected to be organized.  Specifically, for the `--classpath` arg in `preprocess_chunk_img.py`.

**Comment by ZER-0-NE** [comment]
Yeah. About that, I think we should mail Dan asking him the actual classification for all the possible pods I've mentioned in the Readme. I'll update as soon as we get the info.

**Comment by yosoyjay** [comment]
Looking at this, I think if you just move the text from the main README to one specifically for the the preprocessing and this will be all wrapped up. @ZER-0-NE
